### ISSUE TITLE
Optional rendering

### ISSUE THREAD

**Issue by jgaskins** [clearwater-rb/clearwater#15]
One awesome efficiency feature would be to opt out of rendering a component that hasn't changed, such as a static component. In these cases, we'd want to cache the return value of `render` and just return that.

There are a few technical hindrances to this, though. First of all, components instantiated from within other components have no way of knowing what their previous value was because those components are thrown away after rerendering. For example:

```ruby
class Layout
  include Clearwater::Component

  def render
    div(nil, [
      Menu.new
    ])
  end
end
```

In this example, the `Menu` component has no idea where it came from, so it doesn't realize it needs to be cached and it has no way to cache itself even if it did.

Second, caching the values of all these render calls may not be cheap. We'll need to benchmark memory usage.

**Comment by jgaskins** [comment]
Throwing around more ideas here…

Cacheable components may require storing the component on the parent component or in some kind of component registry. Storing cacheable children on the parent may not be a horrible idea since it localizes the storage. It's currently the only way for child components to maintain any sort of state, but the component registry might open up new possibilities for that.

I'm afraid of a component registry expanding too quickly and taking up too much RAM, especially on older mobile devices that may only have 512MB total. If we went this route, we'd have to have some way of knowing which component instances will no longer be displayed and delete them so they can be garbage-collected.

We could probably implement a mixin to add the caching behavior, something like this:

```ruby
module Clearwater
  class CachedRender
    def cached_render
      @cached_render ||= render
    end
  end
end
```

This would allow components that _can_ maintain state to do it with their rendered body. Then maybe we could add another case in the `Component#tag` method to check for `respond_to?(:cached_render)`. I'm concerned about adding more functionality to that method, though, because that method needs to be as lightweight as possible (it is potentially called thousands of times per render) and I'm not sure how expensive `respond_to?` is in Opal. I think it might be worth experimenting and benchmarking.

**Comment by jgaskins** [comment]
@aemadrid Moving the conversation about optional rendering [the other thread](https://github.com/clearwater-rb/clearwater/issues/17#issuecomment-102106769) into this one because it pertains more to this issue.

> I'm guessing that you were targeting caching static content but I'm more concerned with dealing with lots of smaller objects. But I can see that the component could be smarter and digest what it should show itself and be smart about it (immutable objects, smart filtering, etc).

Indeed. The component not regenerating a virtual DOM tree because it's showing static content and not regenerating a virtual DOM tree because the data that virtual DOM tree depends on are functionally equivalent.

Here's an example of a static component caching itself:

```ruby
class AppHeader
  include Clearwater::Component

  def render
    @content ||= header(nil, [
      h1(nil, 'MyAppName'),
      nav({ class_name: 'main-nav' }, [
        Link.new({ href: '/' }, 'Home'),
        Link.new({ href: '/' }, 'Blog'),
        Link.new({ href: '/' }, 'Something else'),
      ]
    ])
  end
end
```

And here's how you might do the same with a component that uses variable state. This is just a brain dump, not something I've actually used, but it should work.

```ruby
class ArticleComponent
  include Clearwater::Component

  attr_reader :cached_render

  def render
    if article_changed?
      render_article
    else
      cached_render
    end
  end

  def render_article
    @previous_article = article
    @cached_render = article(nil, [
      h1(nil, article.title),
      section(nil, article.body),
    ])
  end

  # Get the article based on the path, such as /articles/123
  def article
    ArticleStore.find(params[:article_id])
  end

  def article_changed?
    article != @previous_article
  end
end
```

That's a fair bit of boilerplate to check dependencies. I'd like to make caching a first-class citizen to abstract a lot of the code that would be pretty common in caching scenarios. I wonder React's idea of using a method might just be the best one.

Note that, in this example, you'd be caching based on _which_ article is being rendered. If you want to rerender when the article itself is modified via Pusher, the dependency is actually the _attributes_ of that article.

**Comment by aemadrid** [comment]
Sounds promising. I'm guessing fingerprinting the article would help in making the decision if they are the same article but with different data a lot easier.

**Comment by jgaskins** [comment]
Very likely, but I think that's a decision for the individual component. I just wanted to address the Pusher-update situation you brought up in the other thread.

**Comment by aemadrid** [comment]
Makes sense. It could be a pusher update or a periodic timer refreshing the data.

**Comment by fazibear** [comment]
I'm just curious how this caching works. If you have something like this:
```
route '/articles/:article_id' => ArticleComponent.new
```
On every render there is a new instance of `ArticleComponent` and instace variable cache don's exists ?

**Comment by jgaskins** [comment]
Components that act as routing targets live as long as the app does, so they're not instantiated on every render. This lets you cache things in their instance variables without storing them in some global data store.

Components instantiated by routing targets on render may be cached or they may decide to pick up a fresh version each time. It's up to you for each component.

So far, it seems to be a good idea to store UI state on the components themselves, so it's a good thing the components can stick around if you need them. App state, on the other hand, should probably live elsewhere. I made the [`grand_central`](https://github.com/clearwater-rb/grand_central) gem to help out with this.

**Comment by fazibear** [comment]
OK, other example:
```  
def render
    # Element DSL is tag_name(attributes, content)
    # The attributes can be omitted if you don't need to customize the element.
    div({ id: 'foo' }, [
      # Content types:
      h1('Heading'), # Another element
      'Hello, world!',    # String
      123,                # Numeric
      nil,                # Absolutely nothing
      ArticleIndex.new    # Another component
    ])
  end
```

When you render new content for virtual-dom, you have to invoke `render` method. In this example `ArticleIndex` has a `new` method, so render or rerender gives you a new instace of `ArticleIndex`, and cache simply won't work in his case.

**Comment by jgaskins** [comment]
Yep, that's what I meant here:

> Components instantiated by routing targets on render may be cached or they may decide to pick up a fresh version each time. It's up to you for each component.

You can determine whether to use a fresh instance every time from a parent component or recycle the one you used last time. For example:

```ruby
def render
  div([
    article_index
  ])
end

def article_index
  @article_index ||= ArticleIndex.new
end
```

When that code is part of a component that serves as a routing target, that `ArticleIndex` component will be cached and the same instance will be rendered next time. You can cache like this as far down the component tree as you need, but it's really up to the components themselves whether they cache their children.

Using caching like this, combined with the `Clearwater::CachedRender` mixin on the child component, I've cut renders that took 150ms down to 9ms. `CachedRender` caches the final, sanitized vdom node instead of some intermediate representation, so there is no computation required after that. Then you can implement `should_render?` to determine whether to invalidate that cache.

I thought about storing cached components in some global component store (so parent components wouldn't have to know about their children's cacheability), but I haven't yet figured out how to keep from leaking memory that way. I imagine we would need some sort of capped LRU cache or something, but I'm not sure,
