### ISSUE TITLE
First rendering of a CachedRender component failing 

### ISSUE THREAD

**Issue by balmoral** [clearwater-rb/clearwater#45]
I have a Component class which includes CachedRender. Its render method returns another higher level component. This causes a failure in the low level virtual dom rendering (invalid node). 

It appears the problem lies in the `sanitize_content` method which does not recurse when handling a CachedRender component.

The following patch appears to solve the problem:

```
    def self.sanitize_content content
      %x{
        if(content && content.$$class) {
          if(content.$$class === Opal.Array) {
            return #{content.map { |c| `self.$sanitize_content(c)` }};
          } else {
            var render = content.$render;

            if(content.type === 'Thunk' && typeof(content.render) === 'function') {

              // ORIGINAL
              // return content;

              // PATCH
              return self.$sanitize_content(content.$render());

            } else if(render && !render.$$stub) {
              return self.$sanitize_content(content.$render());
            } else {
              return content;
            }
          }
        } else {
          return content;
        }
      }
    end
```

**Comment by jgaskins** [comment]
Crap, I see what you mean. That patch unfortunately looks like it nullifies caching, though. :-) The mixin hooks directly into the vdom engine, so we pass the component to it directly. I'll have a look tomorrow. In the meantime, wrapping your inner component in a div or span should at least get it running.

I'm honestly surprised I've never come across this. I guess I've just never returned another component directly from a `CachedRender` component. This is a great catch and I appreciate the info on reproducing it. :+1:

**Comment by jgaskins** [comment]
Oh, wait, @balmoral did you include both `Clearwater::Component` and `Clearwater::CachedRender`? CachedRender doesn't include Component for you in case you want to use a different component mixin/superclass.

**Comment by balmoral** [comment]
Not sure that it nullifies caching as CachedRender determines whether #sanitize_content is called on subsequent renders.

**Comment by balmoral** [comment]
I had both both Clearwater::Component and Clearwater::CachedRender modules include.

**Comment by jgaskins** [comment]
I was able to reproduce it with the following components:

```ruby
class Layout
  include Clearwater::Component

  def render
    Foo.new
  end
end

class Foo
  include Clearwater::Component
  include Clearwater::CachedRender

  def render
    Bar.new
  end
end

class Bar
  include Clearwater::Component
  include Clearwater::CachedRender

  def render
    p 'hi'
  end
end
```

It looks like I had to return a `CachedRender` from a `CachedRender`. If either `Foo` or `Bar` did not include `CachedRender`, I couldn't reproduce it.
