### ISSUE TITLE
Running things on a server as if there were in the front end seamlessly

### ISSUE THREAD

**Issue by jlebrech** [clearwater-rb/clearwater#5]
Say I something that need to call on the server, could have a route on a backend server which did an RPC style call on that server.

On that server you could have a controller which translates those calls to method calls or even compile an interface that does the connection stuff seamlessly as if you were just calling a local method on a class.

Say in Clearwater you do:

    Server::MyClass.do_class_method(param1, param 2)

and that would send a message to the backend to run that class, and send the result back.

and in clearwater you would just have to set a baseurl and set a session id to send for those requests.

**Comment by jgaskins** [comment]
If I understand you correctly, that's the goal of the API client mentioned in #1. One of the main ideas I had for Clearwater is for it to be just another consumer of your API, similar to an iOS or Android app. I think a good RPC-style abstraction would be interesting, though.

**Comment by jlebrech** [comment]
yes the API mentioned in #1 would be the way to access resources presented
in a Restful way.

My idea is most RPC, like sending rails console commands over the wire with
a permissions layer if that makes sense.

**Comment by krainboltgreene** [comment]
Is this something that still needs to be open?

**Comment by jgaskins** [comment]
Good question. I've had some time to think about this now and, while I think RPC can be a great abstraction, I'm not sure it fits into my overall vision for Clearwater. That vision is basically that the framework provides the necessities for making an app work in the browser:

- URL-based routing
- API client
- some sort of ORM or other data management facility
- rendering
- most likely authentication

Everything else would probably need to be added separately.

@jlebrech I'm not sure the RPC abstraction is used enough to warrant being included in the base framework. I think it'd be fantastic to see an Opal RPC implementation, though, that could be integrated into a Clearwater app. I appreciate the suggestion and your discussion on it, though. :+1:

**Comment by jlebrech** [comment]
I think it should be a side project, it would be compatible with volt too
