### ISSUE TITLE
Statefull component in combination with CachedRender

### ISSUE THREAD

**Issue by johnsusi** [clearwater-rb/clearwater#67]
I'm working on a `select` component that may contain a huge list of `options` (that may take a long time to render due to translations e.t.c.)

I tried using `CachedRender` and implemented `should_render?` comparing the selected value (the option list is immutable). First change works ok but the second `should_render?` compares against the 'discarded' component in the last render. That might not be a bug but it confused me a bit since I expected it to keep comparing against the component that did the actually rendering. 

This might not be an issue most of the time but it matters when keeping state in the component and having DOM event handlers to keep the state in sync.

Here is a full example

```ruby

require 'clearwater'
require 'clearwater/cached_render'

include Clearwater

class Select

  include Component
  include CachedRender

  attr_reader :options, :value, :onchange

  def initialize(data)
    @options  = data[:options]
    @value    = data[:value]
    @onchange = data[:onchange]
  end

  def should_render?(prev)
    puts "#{self.class.name}:should_render? #{self}:#{value} (prev is #{prev}:#{prev.value})"
    !(prev.options.equal?(options) && prev.value == value)
  end

  def render
    puts "#{self.class.name}:render #{self}"
    children = options.map do |data|
      option({ value: data[:value], selected: value == data[:value] },
             [data[:text]])
    end
    select({ onchange: method(:handle_change) }, children)
  end

  def handle_change(event)
    event.prevent
    @value = event.target.value
    onchange.call(event.target.value)
  end

end

class Layout
  include Component

  def initialize
    @options = [
      { value: 'a', text: 'option 1' },
      { value: 'b', text: 'option 2' },
      { value: 'c', text: 'option 3' }
    ]
    @value = 'a'
  end

  def render
    puts "#{self.class.name}:render #{self}"
    div [item_select, refresh_button]
  end

  def item_select
    Select.new(options: @options, value: @value,
               onchange: -> (value) { @value = value; call })
  end

  def refresh_button
    button({ onclick: -> { call } }, ['refresh'])
  end
end

Application.new(component: Layout.new).call
```

Selecting `option 2` and `option 3` in turn yields

```
# Initial render
Layout:render #<Layout:0x180>
Select:render #<Select:0x18c>

# Select option 2
Layout:render #<Layout:0x180>
should_render? #<Select:0x1a0>:b (prev is #<Select:0x18c>:b)

# Select option 3
Layout:render #<Layout:0x180>
Select:should_render? #<Select:0x1ae>:c (prev is #<Select:0x1a0>:b)
Select:render #<Select:0x1ae>
```

So if this is the expected behaviour perhaps there are better approaches to try out?

**Comment by jgaskins** [comment]
If you'd asked me yesterday what the argument to `should_render?` was, I would've told you it was the original component instance, just as you thought it was. I guess I just haven't noticed it because I've been using stateless components for so long.

I agree this can be confusing; when `should_render?` returns a truthy value, it reuses the last-rendered vdom tree, whose DOM event handlers might retain references to the component that rendered it, but `previous` is a different instance entirely. This means that you're potentially dealing with three component instances: `self`, `previous`, and the last one _actually_ rendered.

I'm happy to chat about this more, but regarding this specific component, I notice in `Select#handle_change`, you're setting `@value` on the `Select` component, and then invoking the callback passed into `Select.new`, which sets the same value into `@value` on the `Layout`, which then gets passed into the _next_ `Select` component instance. Since `Select#value` is the same for both instances, it won't be re-rendered.

**Comment by johnsusi** [comment]
Good, at least my assumptions aren't to far off then ;-)

> I'm happy to chat about this more, but regarding this specific component, I notice in Select#handle_change, you're setting @value on the Select component, and then invoking the callback passed into Select.new, which sets the same value into @value on the Layout, which then gets passed into the next Select component instance. Since Select#value is the same for both instances, it won't be re-rendered.

Actually no that is not what happens (If I understand you correctly). It was what I intended to happen (i.e. I do not want a rerender unless something outside the example changed `@value` in `Layout`. But as you see if you run the example, `render` gets called the second time.

`handle_change` only updates the intial component, not the second one so when selecting option 3 you will have

 - select instance 1  @value: 'c',
 - select instance 2 @value: 'b',
 - select instance 3 @value: 'c'

and instance 2 and 3 get compared, not 1 and 3.

Passing the values to the new component in should_render? is not an option since then I would have to traverse back to the original component to get the actual value (one indirection per render since its creation...).

I guess I could just query the dom for the actual value in this particular example but that feels a bit meh. :)

**Comment by johnsusi** [comment]
For reference, this was what I was trying to achieve. It works with #68 applied

This select-component only renders once and handles changes from both the dom and from the 'app'.

```
class Select

  include Component
  include CachedRender

  attr_reader :options, :value, :onchange, :ref

  def initialize(data)
    @options  = data[:options]
    @value    = data[:value]
    @onchange = data[:onchange]
  end

  def should_render?(prev)
    return true unless prev.options.equal?(options)
    return false if prev.value == value
    if prev.ref.mounted?
      prev.ref.value = value
      return false
    end
    true
  end

  def render
    @ref ||= DOMReference.new
    children = options.map do |data|
      option({ value: data[:value], selected: value == data[:value] },
             [data[:text]])
    end
    select({ onchange: method(:handle_change), ref: @ref }, children)
  end

  def handle_change(event)
    event.prevent
    @value = event.target.value
    onchange.call(event.target.value)
  end

end
```

**Comment by jgaskins** [comment]
Ooooh, I see. I think I misunderstood for exactly the same reason you were confused by this behavior. :-)

There's actually another weird issue with `select` (and other DOM elements with properties that are dependent on their children) in the `virtual-dom` library on first render that I thought might also be affecting this, adding even more confusion. :-) Specifically, if you do `select({ value: 'foo' }, [option, option('foo')])`, it won't select the proper `option` on the first render — you currently have to do it the way you did with `option({ selected: true }, 'foo')` for it to work up front. #66 fixes that by using a vdom engine we own, but the PR needs work to fix the test timeouts.

**Comment by jgaskins** [comment]
Closing this since #68 was merged.
