### ISSUE TITLE
All rails example in README not worked.

### ISSUE THREAD

**Issue by zw963** [clearwater-rb/clearwater#73]
In `Using with Rails` section.

I do follow the README,  but only see `Yay! You’re on Rails!` rails default hello world page,

Thanks

**Comment by jgaskins** [comment]
Good call! Looks like I never updated it for Rails 5 — I mostly use Roda, so it's not something I see often.

The fix is to get Rails to render a blank page by default. To do this, you need to update the app in 3 places:

- a root and catch-all route in `config/routes.rb`
- an empty controller to handle those routes
- an empty view to render that controller action

## `config/routes.rb`
```ruby
root 'home#index'
get '*all' => 'home#index'
```

## `app/controllers/home_controller`
```ruby
class HomeController < ActionController::Base # Doesn't need to be ApplicationController
  def index
  end
end
```

## `app/views/home/index.html.erb`
```html
<!-- This page intentionally left blank -->
```

You can use the Rails generators to generate the controller and view (`rails g controller home index`), but it won't set up the root and catch-all routes, so you'll still need to do that manually.

I'll update the `README` with this info.

**Comment by zw963** [comment]
@jgaskins , yes, I don't remember this is `Rails 5` default behavior or more early.

we don't need delete some template default page now, but we must
add a default route to make it work.

**Comment by zw963** [comment]
I think this should be closed.

**Comment by zw963** [comment]
@jgaskins , I ask one question in gitter, thanks.

**Comment by zw963** [comment]
@jgaskins , Hi, seem like README example still not work completely.

Please see [this](https://github.com/zw963/clearwater_example) project, it worked, but, I have no idea about following code usage:
```rb
router = Clearwater::Router.new do
  route 'articles' => Articles.new do
    route ':article_id' => Article.new
  end
end

MyApp = Clearwater::Application.new(
  component: Layout.new,
  router:    router,
  element:   Bowser.document.body # This is the default target element
)
```

should i access `http://127.0.0.1:3000/articles` to be work? but it failed.

**Comment by zw963** [comment]
Following is error messages:

```sh
ActionController::RoutingError (No route matches [GET] "/articles"):
```

**Comment by zw963** [comment]
@jgaskins , I read more detailed document from [here](https://metaruby.com/t/clearwater-a-front-end-app-framework-in-ruby/121), do you consider copy those document into this github project README?

IMHO, this project README too few document to make a front end newbie (like me) to start. : (

**Comment by jgaskins** [comment]
@zw963 If you add the `get '*all' => 'home#index'` line to your `config/routes.rb`, it should work.

The problem is that Rails is trying to handle that route, but we want to tell Rails to route every request it doesn't understand into your `HomeController` so the Clearwater app can handle it.

**Comment by zw963** [comment]
@jgaskins , worked, thanks

BTW:  all path part in URL, will be access as `params[:all]` in home_controller.
so, maybe add a prefix is better, e.g. `get 'clearwater/*all' => 'home#index'`

**Comment by jgaskins** [comment]
That's a decision to make for the individual app. :-) I prefer to route at the top level if possible. For example, I always do something like this:

```ruby
namespace :api do
  resources :articles
end

root 'home#index'
get '*all' => 'home#index'
```

That way, my API endpoints are matched first and it won't hit the catch-all route at the end on API requests.

If there's more to a Rails app than the single Clearwater app, then I agree that the path should be namespaced. The Clearwater router even has a `namespace` method for just such a scenario. For your `clearwater/*all` example, you'd use this in your router:

```ruby
router = Clearwater::Router.new do
  namespace 'clearwater'

  # routes go here...
end
```

**Comment by zw963** [comment]
> The Clearwater router even has a namespace method for just such a scenario. For your clearwater/*all example, you'd use this in your router:

Cool, thanks, I think I should read through clearwater code base to know this ... clearwater just have a few document ...

**Comment by zw963** [comment]
I think we should add following into github WIKI

https://metaruby.com/t/clearwater-a-front-end-app-framework-in-ruby/121/24
https://github.com/jgaskins/clearwater_todomvc/
https://github.com/clearwater-rb/clearwater/issues/22
